# This is a basic workflow to help you get started with Actions

name: Createfile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Create Folder1
        run: mkdir C:\Folder1
        shell: powershell

      - name: Create File1
        run: New-Item -Path C:\Folder1\file1.txt -ItemType File
        shell: powershell

      - name: Create Folder2
        run: mkdir C:\Folder2
        shell: powershell

      - name: Create File2
        run: New-Item -Path C:\Folder2\file2.txt -ItemType File
        shell: powershell


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
